# -*- coding: utf-8 -*-
"""Project_1 - Band Name Generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aMXGEbnvPBiRd40sIerk-XYd2Pve59Ya
"""

print("Welcome to Band Name Generator")
city = input("What's the name of the city you grew up in?\n")
pet_name = input("What's the name of your pet?\n")
brand_name = print("The name of your band could be: " + city + " " + pet_name)

|